### ISSUE TITLE
feat(mafia/roles): em roles compiled resources 

### ISSUE THREAD

**Issue by pikulet** [UltiMafia/Ultimafia#1]
[original issue | credits](https://github.com/r3ndd/BeyondMafia-Integration/issues/16)

I think lots of people wanna contribute roles so I'm going to paste some resources. Disclaimer: we do not have to implement every exact role and mechanic from em.

**Reference Resources**
- [role description by golbolco](https://docs.google.com/document/d/1A-dgykjdQif1xTFqtSteOk8pF8uFGlNuQDb0Fh5f7Zg)
- [system messages](https://docs.google.com/document/d/1O7_CPUlb0GnyRxTCYpt6WvEbMJSbax5OZGR-K23I66M)

**Pull Request Checklist**
- [ ] Add role description in `data/roles.js`
- [ ] Add role class in `Games/core/types/Mafia/roles/<Alignment>`
- [ ] Add role card (ability) in `Games/core/types/Mafia/roles/cards`
- [ ] (optional) Add role items, effects, meetings `Games/core/types/Mafia/<items/effects/meetings>`

**Comment by Golbolco** [comment]
Consig, Huntsman, Charmer, Telepath, and Whisperer are no longer planned (a few have been reimplemented in other ways)

Last ones to add are Don, Ghostbuster/Exorcist, Librarian
