### ISSUE TITLE
bug(Mafia): demolitionist doesn't work

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1105]
no discernable reason for why demolitionist's bomb did not kill mafia here

https://ultimafia.com/game/uNmofN6bJ/review

**Comment by pikulet** [comment]
works, the mafia who voted first was saved 

![image](https://github.com/UltiMafia/Ultimafia/assets/24848927/e2cfbc8c-3379-4d56-a3f7-917e1cdec6c7)
