### ISSUE TITLE
feat(mafia): Monster/Cult Retool

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#147]
- [x] Faction name: change all references from "Monsters" to Cult (might be easier to change front-facing text only)
- [ ] Roles: Divide Cultist role into two roles: Cult Leader and Cultist
- [ ] Masons: Restore the ability for the Masons to wipe out existing Cultists. This should not affect Cult Leader, Lycan, Cthulhu, or any other Cult roles
- [ ] Cultist: change "MeetWithCultists" meeting to be dependent on the presence of Cult Leader and include all Cult roles in the conversion meeting
- [ ] Cultist: when Cult Leader is not present at the start of the setup, use MeetingMonsters as normal
- [ ] Cult Leader: change "KillSameRoleOnDeath" function to "KillCultistsOnDeath" function
- [ ] Cards: retain legacy "KillSameRoleOnDeath" function for possible uses in the future
- [x] Modifiers: Humble Cult roles appear as Cultist
- [x] Modifiers: Scatterbrained Cult roles appear as Lycan (? Might want to use /v/illage's solution instead)
- [x] Refactor: move Medusa to Cult faction
- [x] Possible new role: For parity purposes Cult might need a Mastermind/Autocrat equivalent, which could be fun. Will need to expand upon later and speak to Meira/Ruviz

**Comment by pikulet** [comment]
[ruviz document](https://docs.google.com/document/d/1hOg2ql2iX0o1WsK_G_-jFspQ64G33Qjw/edit#heading=h.vx1227)

**Comment by pikulet** [comment]
@Golbolco I believe this issue is complete, save for Cult leader's ability to enable cult conversion.
