### ISSUE TITLE
feat(UI): Dropdown menus to replace buttons

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1492]
Fsalker has claimed that the front page has too many buttons. One solution? DROPDOWNS!

Acceptance criteria:
- Change the Play | Host | Create Setup | Decks | Create Deck row into a dropdown menu
- Change the Community button into a dropdown menu (forum, users, moderators etc)

Use this component: https://mui.com/material-ui/react-menu/

**Comment by SeanAverS** [comment]
Hello,

I'm interested on working on this. Could I please be assigned this issue? Thanks.

**Comment by SeanAverS** [comment]
Hello,

I'm interested in working on this. Could I please be assigned? Thanks.

**Comment by Golbolco** [comment]
> Hello,
> 
> I'm interested in working on this. Could I please be assigned? Thanks.

Done! Thanks for the help.
