### ISSUE TITLE
feat(core): Anonymous Decks

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#155]
Returning from EM: the ability to upload a set of avatars/nicknames (called cards) for a game, used as part of an "anonymous deck" game setting

- Logistics: Limit on cards should be 50 to match player cap. Additional cards in a deck requires coins (since they take up player storage)
- [x] #167 
- [x] #161
- [x] #160
- [x] #162
- [x] #163
- [x] #164
- Possible: Should all competitive/ranked games be anonymous?
- [x] #165
- [x] #166

**Comment by pikulet** [comment]
#427
