### ISSUE TITLE
feat(mafia): Independent victories by solo players should acknowledge the player who won

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#157]
On late-stage EpicMafia, if a Fool had won the game then the game would print "Golbolco the Fool wins!" instead of just "Fool wins!"

As far as I can tell, the only Independent role on BM where this wouldn't apply is Turkey, since all Turkeys meet and win together, or for roles that don't win at all like Amnesiac and Old Maid.

Very minor issue, but an issue.

**Comment by pikulet** [comment]
Fixed #603
