### ISSUE TITLE
feat(mafia): Parasite role

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1598]
Acceptance Criteria:
- New role: Parasite
- Cult-sided
- Infests a player on its first night. Will appear dead
- Gains the abilities to vent its infested host and redirect their abilities at night
- If their corpse in the GY is exorcised (https://github.com/UltiMafia/Ultimafia/issues/1599), the Parasite dies
- If the host is killed, the parasite dies

paging @NouSixXD

**Comment by SawJester** [comment]
I'm working on this.
