### ISSUE TITLE
feat(mafia): Merge One Night into Mafia

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1607]
Acceptance Criteria:
- Port over "Excess Roles" option and One Night-exclusive roles and mechanics to the main Mafia game mode
- Deprecate the Learn/Games One Night tab
- Add "One Night" win criteria as a new game option for setup creation

**Comment by SawJester** [comment]
- [ ] Excess Roles- One Night does it a bit differently but functionally the same.
- [ ] OneNight Wincon
- [ ] No Evils Mode

Roles

- [ ] Villager - Added
- [ ] Hunter - Added
- [ ] Mason - Added as Templar
- [ ] Seer - added as Tarotist
- [ ] Robber - 
- [ ] Troublemaker
- [ ] Insomniac - I don't understand this role
- [ ] Werewolf - Kind of Added as Cultist/Mafioso
- [ ] Minion - Kind of Added as Traitor/Grouch
- [ ] Drunk
- [ ] Tanner - Added as Fool
- [ ] Doppelganger

**Comment by SawJester** [comment]
Currently make the roles.

**Comment by Golbolco** [comment]
Looking at unimplemented material from One Night expansions, starting with Alien:

- [ ] Alien faction - Action dependent on a percentage, could be implemented as a gamechanging role within Mafia faction but kind of weird
- [ ] Synthetic - basically Clown
- [ ] Groob and Zerb - basically Rival

- [ ] Mortician - Wins if either neighbor dies; is this good, or just another Warlock/Lyncher variant?
( Could actually add some roles as alternative modes for existing roles when in One Night)

- [ ] Blob - basically Lover
- [ ] Cow - basically a slightly weaker Empath
- [ ] Exposer - publicly reveals 1-3 excess roles, not sure we have a role like this
- [ ] Leader - basically Invisible Man or "Witness/Little Girl" from many other Mafia variants; not recommended
- [ ] Oracle - very complicated, seems like the reverse of a MafiaScum Oracle https://wiki.mafiascum.net/index.php?title=Oracle
- [ ] Psychic - Random role viewer, seems superfluous
- [ ] Rascal - very limited role copier, low-value

**Comment by Golbolco** [comment]
Daybreak:

- [ ] Sentinel - basically Shrink
- [ ] Apprentice Seer - better to add MafiaScum Backup https://wiki.mafiascum.net/index.php?title=Backup as a modifier (role with backup modifier is inactive/acts as alignment's vanilla until someone with the same role dies)
- [ ] Paranormal Investigator - looks at excess roles, converts if one of them is not Village to the non-village role
- [ ] Witch - swaps someone with an excess role
- [ ] Village idiot - rotates entire game's roles left or right along the Table
- [ ] Revealer - basically Photographer, Oracle, Gemcutter's orb etc etc
- [ ] Curator - Annoying role, low-value Santa
- [ ] Bodyguard - prevents the majority vote target from dying, shifts to kill the person with the second most votes (call it Lifeguard?)
- [ ] Alpha Wolf - Pedagogue/Enchantress but less fun
- [ ] Mystic Wolf - basically Stalker
- [ ] Dream Wolf - basically (Lone) Mafioso/Cultist

**Comment by Golbolco** [comment]
Bonus Roles:

- [ ] Aura Seer - can see anyone whose roles changed or who knows another person's (or an excess) role; seems very weak, not sure it's worth adding
- [ ] Prince - cannot be condemned, next-most voted person will be condemned instead if they are majority
- [ ] Cursed - similar to Turncoat
- [ ] Apprentice Tanner - basically Sidekick on Fool
- [ ] Beholder - knows who Seer is, low-value
- [ ] Squire - basically Invisible Man or "Witness/Little Girl" style role
- [ ] Thing - basically Vegan but restricted to their neighbors
- [ ] Body Snatcher - basically a One Shot Cult Leader, or a Yakuza who doesn't die
- [ ] Nostradamus - same as Paranormal Investigator, but looks at 3 cards instead of 2
- [ ] Empath - basically impossible to add

**Comment by Golbolco** [comment]
Vampire:

- [ ] Gremlin - Philosopher but for Excess instead of Banished roles, low-value
- [ ] Vampire - basically Cultist
- [ ] Master - same as Prince, but evil
- [ ] Count - basically Hooker/Succubus
- [ ] Renfield - not relevant, because marks would be items in our engine
- [ ] Cupid - same as Astrologer
- [ ] Diseased - basically Old Maid
- [ ] Instigator - changes their target's wincon forcing them to bus a teammate; cool in theory, but I foresee balancing issues
- [ ] Priest - basically Nurse
- [ ] Assassin - basically Lyncher/Warlock
- [ ] Apprentice Assassin - basically Sidekick on Lyncher/Warlock
- [ ] Marksman - basically a Detective/Snoop hybrid
- [ ] Pickpocket - basically Waitress
- [ ] Gremlin - basically Mediator but with marks

Not convinced Marks would be a worthy addition to the game, they are an itemized form of role converters or other information usually handled by effects and variables
