### ISSUE TITLE
Fool joints with Mafia when lynched in 3way

### ISSUE THREAD

**Issue by viggyn** [UltiMafia/Ultimafia#1759]
doesn't seem like intended interaction but cheese strat is intentional so who knows. Fool win conditions hinder the balance of ranked setups containing the fool role

Best of luck fixing your website

**Comment by SawJester** [comment]
Fool always Joints with mafia if Mafia gets Maj at the same time the fool is condemned. This is currently Intended. I would like to remove Fool joint wins with mafia/cult but currently Its a feature.
