### ISSUE TITLE
Broker weird interaction with fool if day start

### ISSUE THREAD

**Issue by NouSixXD** [UltiMafia/Ultimafia#1804]
https://ultimafia.com/game/KMUQ4gaGY/review

3p (mafioso, broker, fool) setup with day start
d1 mafioso gets lynched and game doesn't end
d2 broker gets lynched and game doesn't end although fool is the only one left alive

Issue is related to day start, brokers code has some statement that checks for nights, but since game starts on a day it doesn't go through. But I'd think his code would go through on first night after mafioso gets lynched, so this interaction is still weird to me.

**Comment by SawJester** [comment]
Fixed
