### ISSUE TITLE
feat(Mafia): De-modifying default roles

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#479]
## Story

For the sake of consistency and in keeping with Role Patrol guidelines, existing Mafia roles should be simplified so that setup creators are given maximum freedom in customizability for their roles and setups.
 
## For Admins

Once the pull request is merged, make a public announcement for users to update their setups if the need arises. Include list of affected roles:
- Blinder
- Crank
- Hitman
- Interrogator
- Silencer
- Slasher
- Sniper
- Thief
- Gallis
- King
- Loudmouth
- Sleepwalker
- Trickster
- Village Idiot
- Enchantress
- Governor
- Resurrectionist
- Necromancer
- Janitor
- Housekeeper
- Waitress

## Acceptance Criteria

- Modifiers stack up to three
- Update all Mafia cards to include MeetingMafia, save for Clown
- Update all role cards for night meeting actions to recur an unlimited number of times
- Update all Village cards to remove Humble
- Update OneShot.js to account for day actions (Overturn, etc.) as well as night actions
- Bugfix OneShot.js to ignore a no-action vote when counting if a player has used up their ability

**Comment by pikulet** [comment]
Depends on #14
