### ISSUE TITLE
feat(Mafia): Monkey 2.0

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#481]
## Story

Monkey on Rend's engine is implemented differently than it was on EpicMafia. Monkey had a second night action and was able to use the first stolen action on another player.

## Acceptance Criteria

- Bugfix: Monkey interacts poorly with roles that use data (eg. Alchemist)
- StolenAction card for performing the action blocked by StealAction card upon another player

**Comment by pikulet** [comment]
#605
