### ISSUE TITLE
Add in-game Music

### ISSUE THREAD

**Issue by Fsalker** [UltiMafia/Ultimafia#485]
## Story

as a **PLAYER**
i want to **HEAR MUSIC** in-game

## Resources

- **[track list (click me)](https://soundcloud.com/user-972664097/sets/epicmafia-soundtrack)**
- [**soundcloud playlist downloader**](https://downloadsound.cloud/playlist)

## Acceptance Criteria

- all **tracks** must be clean, **high-quality** (minimum 192kbps)
- all tracks must be used _(NonMeetingMafiaNM = mafia without night meeting (eg: spy), MafiaCM = Mafia & ClockMaker joint win, ...)_
- **music file paths** should be easily **customizable**, even by **non-technical** contributors _(eg: in constants.js, just like [**slangList.json**](https://github.com/UltiMafia/Ultimafia/blob/master/react_main/src/json/slangList.js))_
- "**Music Volume**" slider exists, right under "**Volume**" _(game > settings > volume)_
- "**Volume**" is renamed into "**Sound Effects Volume**"
- **music** can be **switched on/off** using a new **icon-button** (**[on icon](https://fontawesome.com/v5/icons/music?f=classic&s=solid)**, **[off icon](https://fontawesome.com/v5/icons/volume-mute?f=classic&s=solid)**)

![image](https://github.com/UltiMafia/Ultimafia/assets/16700631/babce1b3-dbdc-43d5-acdf-626d5dc2898c)
![image](https://github.com/UltiMafia/Ultimafia/assets/16700631/beee3777-4b77-4cde-a296-4b31b3bd1a75)

## Background

We need to add role-specific, phase-specific music from Fred's library https://soundcloud.com/user-972664097/sets/epicmafia-soundtrack in order for Mafia games to have ambience and atmosphere for the players

**Comment by pikulet** [comment]
the true ticket

**Comment by Golbolco** [comment]
ayyyy

**Comment by pikulet** [comment]
@Golbolco done?
