### ISSUE TITLE
feat(Mafia): Famine as a Mechanic

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#488]
## Story

Roles turning on esoteric game functions eg. Famine is inconsistent, leads to redundancies in code. Solution: convert Famine to a mechanic/game setting for setup creation page.

## Resources

- **[Golbolco's rambling about Famine](https://ultimafia.com/community/forums/thread/m1weZoazV?reply=SCMtD371f)**

## Acceptance Criteria

- Must use existing Famine code present in BreadGiver.js as basis for new Famine mechanic
- Insert Famine code under game.jsx
- Delete the references to Famine in BreadGiver.js and GiveTurkeyOnDeath.js
- Must not edit TakeTheApple.js, conditionally triggers famine state independent of setup mechanics
- Edit schemas.js to include boolean for Famine, number for breadCount
- Edit popovers.jsx to include info for Famine
- Edit learnMafia.jsx to include Famine under mechanics
- Edit CreateMafiaSetup.jsx to include boolean for Famine, number for breadCount (number range from 2-99)
- Edit setup.js to include boolean for Famine, number for breadCount

**Comment by pikulet** [comment]
@Golbolco When writing a ticket, you should not write which files are required to change as the point. Instead, it should be the expected result e.g.

Edit setup.js to include boolean for Famine, number for breadCount

becomes

Add a configurable option to enable famine in the game
Add a configurable option to select how many breads the players start with
