### ISSUE TITLE
bug: modified Actress will still show as modified when taking on its hidden role

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#589]
Not great, ruins the disguise

**Comment by Golbolco** [comment]
option b) actress to reveal the target's modifier name is better

**Comment by pikulet** [comment]
what's the behavior for actress going on insane cop, miller

some modifiers are also giveaways like dying with Explosive and Armoured

I think actress' role is about copying the suit not modifier 🤔

**Comment by pikulet** [comment]
suit now hides modifier
